'use strict';

export const italianDateTerms = {
  next: ['prossimo', 'prossima'],
  previous: ['scorso', 'scorsa', 'scorsi'],
  last: ['ultimo', 'ultima'],
  yesterday: ['ieri'],
  today: ['oggi'],
  tomorrow: ['domani'],
  after: ['dopo'],
  before: ['altro'],

  within: ['tra', 'fra'],
  ago: ['fa'],
  day: ['giorno', 'giorni'],

  afterTomorrow: ['dopodomani'],
  beforeYesterday: ['altroieri', 'avantieri'],
  week: ['settimana', 'settimane'],
  month: ['mese', 'mesi'],
  months: [
    'gennaio',
    'febbraio',
    'marzo',
    'aprile',
    'maggio',
    'giugno',
    'luglio',
    'agosto',
    'settembre',
    'ottobre',
    'novembre',
    'dicembre',
  ],
  weekDays: ['domenica', 'lunedi', 'martedi', 'mercoledi', 'giovedi', 'venerdi', 'sabato'],
  year: ['anno', 'anni'],
  numbers: [
    'un',
    'due',
    'tre',
    'quattro',
    'cinque',
    'sei',
    'sette',
    'otto',
    'nove',
    'dieci',
    'undici',
    'dodici',
    'tredici',
    'quattordici',
    'quindici',
    'sedici',
    'diciassette',
    'diciotto',
    'diciannove',
    'venti',
    'ventuno',
    'ventidue',
    'ventitré',
    'ventiquattro',
    'venticinque',
    'ventisei',
    'ventisette',
    'ventotto',
    'ventinove',
    'trenta',
    'trentuno',
  ],
};

export const extractorSequence = [
  'absolute',
  'canonical',
  'relativeStep',
  'relativeRange',
  'relativeAbsolute',
  'relativePeriod',
  'relativeWeekDay',
  'relative',
];
